//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainAnalysis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoRawMaterialFileDir {
            get {
                return ((string)(this["AutoRawMaterialFileDir"]));
            }
            set {
                this["AutoRawMaterialFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManualRawMaterialFileDir {
            get {
                return ((string)(this["ManualRawMaterialFileDir"]));
            }
            set {
                this["ManualRawMaterialFileDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManualModelFilePath {
            get {
                return ((string)(this["ManualModelFilePath"]));
            }
            set {
                this["ManualModelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AutoWizardRawFilePath {
            get {
                return ((string)(this["AutoWizardRawFilePath"]));
            }
            set {
                this["AutoWizardRawFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoWizardIsDeleteExistingFile {
            get {
                return ((bool)(this["AutoWizardIsDeleteExistingFile"]));
            }
            set {
                this["AutoWizardIsDeleteExistingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25,30,35,40")]
        public string AutoWizardTopicNumberArray {
            get {
                return ((string)(this["AutoWizardTopicNumberArray"]));
            }
            set {
                this["AutoWizardTopicNumberArray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public string AutoWizardMaxIteration {
            get {
                return ((string)(this["AutoWizardMaxIteration"]));
            }
            set {
                this["AutoWizardMaxIteration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManualWizardModelFilePath {
            get {
                return ((string)(this["ManualWizardModelFilePath"]));
            }
            set {
                this["ManualWizardModelFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ManualWizardRawFilePath {
            get {
                return ((string)(this["ManualWizardRawFilePath"]));
            }
            set {
                this["ManualWizardRawFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManualWizardIsDeleteExistingFile {
            get {
                return ((bool)(this["ManualWizardIsDeleteExistingFile"]));
            }
            set {
                this["ManualWizardIsDeleteExistingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoIsDeleteExistingFile {
            get {
                return ((bool)(this["AutoIsDeleteExistingFile"]));
            }
            set {
                this["AutoIsDeleteExistingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ManualIsDeleteExistingFile {
            get {
                return ((bool)(this["ManualIsDeleteExistingFile"]));
            }
            set {
                this["ManualIsDeleteExistingFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExtraManualSearchTerms {
            get {
                return ((string)(this["ExtraManualSearchTerms"]));
            }
            set {
                this["ExtraManualSearchTerms"] = value;
            }
        }
    }
}
